# Configuración de Streamlit - Tema Light Oficial con colores mexicanos

[theme]
base = "light"
primaryColor = "#7D1F3A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
# enableCORS y enableXsrfProtection se dejan en sus valores por defecto
# para evitar conflictos de seguridad
